service:
  name: wilmon-travel-service

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 128
  stage: ${opt:stage, 'dev'}
  region: ap-northeast-2
  profile: dev-sls
  environment:
    WILMON_TRAVELS_TABLE: ${self:custom.WilmonTravelsTable.name}
    TRAVEL_PLACES_TABLE: ${self:custom.TravelPlacesTable.name}
    REDIS_HOST: ${file(secrets.yml):Redis.host}
    REDIS_PORT: ${file(secrets.yml):Redis.port}
    REDIS_PWD: ${file(secrets.yml):Redis.password}
    PLACE_IDS_SET: 'TravelPlacesIds'
    AUTH0_DOMAIN: ${file(secrets.yml):Auth0.domain}
    AUTH0_CLIENT_ID: ${file(secrets.yml):Auth0.clientId}
    AUTH0_CLIENT_SECRET: ${file(secrets.yml):Auth0.clientSecret}
    AUTH0_AUDIENCE: ${file(secrets.yml):Auth0.audience}
    MAIL_QUEUE_URL: ${self:custom.MailQueue.url}
    MAIL_SOURCE: ${file(secrets.yml):Mail.source}

resources:
  Resources:
    WilmonTravelsTable: ${file(resources/WilmonTravelsTable.yml):Table}
    TravelPlacesTable: ${file(resources/TravelPlacesTable.yml):Table}
    CreateTravelLambdaRole: ${file(resources/roles/CreateTravelLambdaRole.yml):Role}
    GetTravelsLambdaRole: ${file(resources/roles/GetTravelsLambdaRole.yml):Role}

functions:
  getTravels:
    handler: src/handlers/getTravels.handler
    role: GetTravelsLambdaRole
    events:
      - http:
          method: GET
          path: /travels
          cors: true
          authorizer: ${self:custom.authorizer}
  createTravel:
    handler: src/handlers/createTravel.handler
    role: CreateTravelLambdaRole
    events:
      - http:
          method: POST
          path: /travel
          authorizer: ${self:custom.authorizer}
  autoGenarateTravels:
    handler: src/handlers/autoGenerateTravels.handler
    role: CreateTravelLambdaRole
    # events:
    #   - schedule: cron(30 * * * ? *)

custom:
  authorizer:
    arn: arn:aws:lambda:#{AWS::Region}:#{AWS::AccountId}:function:wilmon-travel-auth-service-${self:provider.stage}-auth
  WilmonTravelsTable:
    name: !Ref WilmonTravelsTable
    arn: !GetAtt WilmonTravelsTable.Arn
  TravelPlacesTable:
    name: !Ref TravelPlacesTable
    arn: !GetAtt TravelPlacesTable.Arn
  MailQueue:
    arn: ${cf:notification-service-${self:provider.stage}.MailQueueArn}
    url: ${cf:notification-service-${self:provider.stage}.MailQueueUrl}
  bundle:
    linting: false
    externals:
      - superagent-proxy
      - formidable
