service:
  name: wilmon-travel-service

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 128
  stage: ${opt:stage, 'dev'}
  region: ap-northeast-2
  profile: dev-sls
  environment:
    WILMON_TRAVELS_TABLE: ${self:custom.WilmonTravelsTable.name}

resources:
  Resources:
    WilmonTravelsTable: ${file(resources/WilmonTravelsTable.yml):Table}
    CreateTravelLambdaRole: ${file(resources/role/CreateTravelLambdaRole.yml):Role}

functions:
  createTravel:
    handler: src/handlers/createTravel.handler
    role: CreateTravelLambdaRole
    events:
      - http:
          method: POST
          path: /travel

custom:
  WilmonTravelsTable:
    name: !Ref WilmonTravelsTable
    arn: !GetAtt WilmonTravelsTable.Arn
  bundle:
    linting: false
