Role:
  Type: AWS::IAM::Role
  Properties:
    RoleName: CreateTravelLambdaRole
    AssumeRolePolicyDocument:
      Version: '2012-10-17'
      Statement:
        - ${file(statements/LambdaAssumeRole.yml):Statement}
    Policies:
      - PolicyName: createTravelLambdaPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - ${file(statements/LambdaBasicDefault.yml):Statement}
            - ${file(statements/TravelsTableWrite.yml):Statement}
            - ${file(statements/PlacesTableRead.yml):Statement}
            - ${file(statements/MailQueueSend.yml):Statement}
