Role:
  Type: AWS::IAM::Role
  Properties:
    RoleName: GetTravelsLambdaRole
    AssumeRolePolicyDocument:
      Version: '2012-10-17'
      Statement:
        - ${file(statements/LambdaAssumeRole.yml):Statement}
    Policies:
      - PolicyName: getTravelsLambdaPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - ${file(statements/LambdaBasicDefault.yml):Statement}
            - ${file(statements/TravelsTableRead.yml):Statement}
